name: Deploy FibonacciK8s
on:
  push:
    branches:
      - main
      
env:
  SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} --password-stdin
          docker build -t two4onebill/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true two4onebill/react-test npm test

      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: fibonacci-k8s-436112

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: fibonacci-k8s-cluster
          location: us-east1-b

      - name: Build
        run: |-
          docker build -t two4onebill/fibonacci-k8s-client-gh:latest -t two4onebill/fibonacci-k8s-client-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t two4onebill/fibonacci-k8s-server-gh:latest -t two4onebill/fibonacci-k8s-server-gh:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t two4onebill/fibonacci-k8s-worker-gh:latest -t two4onebill/fibonacci-k8s-worker-gh:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push two4onebill/fibonacci-k8s-client-gh:latest
          docker push two4onebill/fibonacci-k8s-server-gh:latest
          docker push two4onebill/fibonacci-k8s-worker-gh:latest

          docker push two4onebill/fibonacci-k8s-client-gh:${{ env.SHA }}
          docker push two4onebill/fibonacci-k8s-server-gh:${{ env.SHA }}
          docker push two4onebill/fibonacci-k8s-worker-gh:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=two4onebill/fibonacci-k8s-server-gh:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=two4onebill/fibonacci-k8s-client-gh:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=two4onebill/fibonacci-k8s-worker-gh:${{ env.SHA }}