name: Deploy Fibonacci
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t two4onebill/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true two4onebill/react-test npm test

      - run: docker build -t two4onebill/fibonacci-docker-client ./client
      - run: docker build -t two4onebill/fibonacci-docker-nginx ./nginx
      - run: docker build -t two4onebill/fibonacci-docker-api ./server
      - run: docker build -t two4onebill/fibonacci-docker-worker ./worker

      - run: docker push two4onebill/fibonacci-docker-client
      - run: docker push two4onebill/fibonacci-docker-nginx
      - run: docker push two4onebill/fibonacci-docker-api
      - run: docker push two4onebill/fibonacci-docker-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: fibonacci-docker
          environment_name: Fibonacci-docker-env
          existing_bucket_name: frontendbucket17
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip